---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-php
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  php.ini: |
    memory_limit = {{ index .Values "php" "max-upload-size" | default "256M" }}
    upload_max_size = {{ index .Values "php" "max-upload-size" | default "256M" }}
    post_max_size = {{ index .Values "php" "max-upload-size" | default "256M" }}
    upload_max_filesize = {{ index .Values "php" "max-upload-size" | default "256M" }}
    max_execution_time = 600
    max_input_time = 1200
    opcache.enable = 1
    opcache.validate_timestamps = 1
    opcache.revalidate_freq = 60
    opcache.max_accelerated_files = 10000
    opcache.memory_comsumption = 64
    opcache.interned_strings_buffer = 8
    opcache.fast_shutdown = 1
{{- if (index .Values "php" "additional-ini") }}
{{ index .Values "php" "additional-ini" | indent 4 }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-wp-config
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  wp-config-common.php: |
    <?php
    define('WP_ALLOW_MULTISITE', true );
    define('MULTISITE', true);
    define('SUBDOMAIN_INSTALL', true);
{{- if and .Values.wp .Values.wp.domain }}
    define('DOMAIN_CURRENT_SITE', '{{- .Values.wp.domain }}');
{{- end }}
    define('PATH_CURRENT_SITE', '/');
    define('SITE_ID_CURRENT_SITE', 1);
    define('BLOG_ID_CURRENT_SITE', 1);
  htaccess: |
    <IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.php$ - [L]

    # add a trailing slash to /wp-admin
    RewriteRule ^wp-admin$ wp-admin/ [R=301,L]

    RewriteCond %{REQUEST_FILENAME} -f [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^ - [L]
    RewriteRule ^(wp-(content|admin|includes).*) $1 [L]
    RewriteRule ^(.*\.php)$ $1 [L]
    RewriteRule . index.php [L]
    </IfModule>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-wp
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if (index .Values "percona-xtradb-cluster" "enabled") }}
  WORDPRESS_DB_HOST: {{ .Release.Name }}-pxc.{{ .Release.Namespace }}:3306
  WORDPRESS_DB_USER: {{ index .Values "percona-xtradb-cluster" "mysqlUser" }}
  WORDPRESS_DB_NAME: {{ index .Values "percona-xtradb-cluster" "mysqlDatabase" }}
{{- end }}
{{- if .Values.env }}
{{ toYaml .Values.env | indent 2 }}
{{- end }}
