---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-php
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  php.ini: |
    memory_limit = {{ index .Values "php" "max-upload-size" | default "256M" }}
    upload_max_size = {{ index .Values "php" "max-upload-size" | default "256M" }}
    post_max_size = {{ index .Values "php" "max-upload-size" | default "256M" }}
    upload_max_filesize = {{ index .Values "php" "max-upload-size" | default "256M" }}
    max_execution_time = 600
    max_input_time = 1200
    opcache.enable = 1
    opcache.validate_timestamps = 1
    opcache.revalidate_freq = 60
    opcache.max_accelerated_files = 10000
    opcache.memory_comsumption = 64
    opcache.interned_strings_buffer = 8
    opcache.fast_shutdown = 1
{{- if (index .Values "php" "additional-ini") }}
{{ index .Values "php" "additional-ini" | indent 4 }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-wp
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.tags.database }}
  WORDPRESS_DB_HOST: {{ .Release.Name }}-mariadb.{{ .Release.Namespace }}:3306
  WORDPRESS_DB_USER: {{ index .Values "mariadb" "db" "user" }}
  WORDPRESS_DB_NAME: {{ index .Values "mariadb" "db" "name" }}
{{- else }}
  WORDPRESS_DB_HOST: {{ .Values.externalDB.host | quote }}
  WORDPRESS_DB_USER: {{ .Values.externalDB.user | quote }}
  WORDPRESS_DB_NAME: {{ .Values.externalDB.name | quote }}
{{- end }}
  WORDPRESS_DISABLE_WP_CRON: "true"
  WORDPRESS_WP_TABLE_PREFIX: wp_
  WORDPRESS_WP_DEBUG: "false"
  WORDPRESS_DB_CHARSET: "utf-8"
  WORDPRESS_DB_COLLATE: ""
{{- if .Values.env }}
{{ toYaml .Values.env | indent 2 }}
{{- end }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-wp
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  wp-config.php: |
    <?php
    /**
     * The base configuration for WordPress
     *
     * The wp-config.php creation script uses this file during the
     * installation. You don't have to use the web site, you can
     * copy this file to "wp-config.php" and fill in the values.
     *
     * This file contains the following configurations:
     *
     * * MySQL settings
     * * Secret keys
     * * Database table prefix
     * * ABSPATH
     *
     * @link https://codex.wordpress.org/Editing_wp-config.php
     *
     * @package WordPress
     */

    // ** MySQL settings - You can get this info from your web host ** //
    /** The name of the database for WordPress */
    define('DB_NAME', getenv('WORDPRESS_DB_NAME'));

    /** MySQL database username */
    define('DB_USER', getenv('WORDPRESS_DB_USER'));

    /** MySQL database password */
    define('DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD'));

    /** MySQL hostname */
    define('DB_HOST', getenv('WORDPRESS_DB_HOST'));

    /** Database Charset to use in creating database tables. */
    define('DB_CHARSET', getenv('WORDPRESS_DB_CHARSET'));

    /** The Database Collate type. Don't change this if in doubt. */
    define('DB_COLLATE', getenv('WORDPRESS_DB_COLLATE'));

    /**#@+
     * Authentication Unique Keys and Salts.
     *
     * Change these to different unique phrases!
     * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
     * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
     *
     * @since 2.6.0
     */
    define('AUTH_KEY',         getenv('WORDPRESS_AUTH_KEY'));
    define('SECURE_AUTH_KEY',  getenv('WORDPRESS_SECURE_AUTH_KEY'));
    define('LOGGED_IN_KEY',    getenv('WORDPRESS_LOGGED_IN_KEY'));
    define('NONCE_KEY',        getenv('WORDPRESS_NONCE_KEY'));
    define('AUTH_SALT',        getenv('WORDPRESS_AUTH_SALT'));
    define('SECURE_AUTH_SALT', getenv('WORDPRESS_SECURE_AUTH_SALT'));
    define('LOGGED_IN_SALT',   getenv('WORDPRESS_LOGGED_IN_SALT'));
    define('NONCE_SALT',       getenv('WORDPRESS_NONCE_SALT'));
    /**#@-*/

    /**
     * WordPress Database Table prefix.
     *
     * You can have multiple installations in one database if you give each
     * a unique prefix. Only numbers, letters, and underscores please!
     */

    $table_prefix  = getenv('WORDPRESS_WP_TABLE_PREFIX');

    /**
     * For developers: WordPress debugging mode.
     *
     * Change this to true to enable the display of notices during development.
     * It is strongly recommended that plugin and theme developers use WP_DEBUG
     * in their development environments.
     *
     * For information on other constants that can be used for debugging,
     * visit the Codex.
     *
     * @link https://codex.wordpress.org/Debugging_in_WordPress
     */
    define('WP_DEBUG', getenv('WORDPRESS_WP_DEBUG'));
    define('DISABLE_WP_CRON', getenv('WORDPRESS_DISABLE_WP_CRON'));
    // If we're behind a proxy server and using HTTPS, we need to alert Wordpress of that fact
    // see also http://codex.wordpress.org/Administration_Over_SSL#Using_a_Reverse_Proxy
    if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $_SERVER['HTTPS'] = 'on';
    }
    /* That's all, stop editing! Happy blogging. */

    /** Absolute path to the WordPress directory. */
    if ( !defined('ABSPATH') )
            define('ABSPATH', dirname(__FILE__) . '/');

    /** Sets up WordPress vars and included files. */
    require_once(ABSPATH . 'wp-settings.php');
