---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-php
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  php.ini: |
    memory_limit = {{ index .Values "php" "max-upload-size" | default "256M" }}
    upload_max_size = {{ index .Values "php" "max-upload-size" | default "256M" }}
    post_max_size = {{ index .Values "php" "max-upload-size" | default "256M" }}
    upload_max_filesize = {{ index .Values "php" "max-upload-size" | default "256M" }}
    max_execution_time = 600
    max_input_time = 1200
    opcache.enable = 1
    opcache.validate_timestamps = 1
    opcache.revalidate_freq = 60
    opcache.max_accelerated_files = 10000
    opcache.memory_comsumption = 64
    opcache.interned_strings_buffer = 8
    opcache.fast_shutdown = 1
{{- if (index .Values "php" "additional-ini") }}
{{ index .Values "php" "additional-ini" | indent 4 }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "id-wordpress.fullname" . }}-wp
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.tags.database }}
  WORDPRESS_DB_HOST: {{ .Release.Name }}-pxc.{{ .Release.Namespace }}:3306
  WORDPRESS_DB_USER: {{ index .Values "percona-xtradb-cluster" "mysqlUser" }}
  WORDPRESS_DB_NAME: {{ index .Values "percona-xtradb-cluster" "mysqlDatabase" }}
{{- else }}
  WORDPRESS_DB_HOST: {{ .Values.externalDB.host | quote }}
  WORDPRESS_DB_USER: {{ .Values.externalDB.name | quote }}
  WORDPRESS_DB_NAME: {{ .Values.externalDB.user | quote }}
{{- end }}
{{- if .Values.env }}
{{ toYaml .Values.env | indent 2 }}
{{- end }}
