apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "id-wordpress.fullname" . }}
  labels:
    app: {{ template "id-wordpress.name" . }}
    chart: {{ template "id-wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "id-wordpress.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "id-wordpress.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: wp-config
          configMap:
            name: {{ template "id-wordpress.fullname" . }}-wp-config
        - name: php-ini
          configMap:
            name:  {{ template "id-wordpress.fullname" . }}-php
        - name: wordpress-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "id-wordpress.fullname" .) }}
        {{- else }}
            emptyDir: {}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "id-wordpress.fullname" . }}-wp
            - secretRef:
                name: {{ template "id-wordpress.fullname" . }}-wp
{{- if .Values.tags.database }}
          env:
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: mariadb-password
{{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-data
              subPath: html
            - name: php-ini
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: wp-config
              mountPath: /var/www/wp_config.php
              subPath: wp_config.php
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
