# Default values for id-wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wordpress
  tag: 4.9.8
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# used only if percona-xtradb-cluster is disabled
externalDB:
  host: ""
  name: ""
  user: ""
  password: ""

php:
  max-upload-size: 256M
  additional-ini: # multi-line string with additional php.ini contents

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    kubernetes.io/ingress.class: nginx-private-test
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "wplbsession"
    nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
  path: /
  hosts:
    - cleanslate.introspectdev.io
  tls:
    - secretName: cleanslate-introspectdev-io
      hosts:
        - cleanslate.introspectdev.io
persistence:
  enabled: true
  # this doesn't matter if nfs-server-provisioner creates a
  # storageClass - i.e. it will defer to that value if it's created
  storageClass: "nfs-04"
  accessMode: ReadWriteMany
  size: 32Gi


resources:
  requests:
    cpu: 500m
    memory: 512Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  WORDPRESS_TABLE_PREFIX: wp_
  WORDPRESS_DEBUG: "0"

secrets:
  WORDPRESS_AUTH_KEY: "`)bnh-sgJ5<wT/W}<XXJtsjf(Go@^3F?_bLQ/@pcxS$221[ra76&(72_}l;{I)#p"
  WORDPRESS_SECURE_AUTH_KEY: "L@@tzvp#]hJ}1*]6P?b$A`b|elR`7H;*Tab^>erAwLroo*E_O0|;[cB1nAk_B)k1"
  WORDPRESS_LOGGED_IN_KEY: "P)}v@-8FwRq2=L?({^8C6p:,Z^JUsNXq`>5r0cu-Nb>())2``,qa_8/I6^lspd:A"
  WORDPRESS_NONCE_KEY: "rD}JSHanNw}Jrh&pgwTz<q?Qls8qyuqSKTBLRM6C$UR/:^WA*RF4a|IoG0+SF4OQ"
  WORDPRESS_AUTH_SALT: "tu(0{$rBz^ewadM/yE4FyY)j=z(:aCCS9cF,4vI5??quUFr)q!:!.;hVDJ^&OBEI"
  WORDPRESS_SECURE_AUTH_SALT: "nckG4&$RQ-_0}UBKoVyP6W[RNB5LIV#Rxs#<NFeG6=:>;5%bO*2>g{ujI/2*2nP["
  WORDPRESS_LOGGED_IN_SALT: "}fwy<?*r<u7yHE[aoKiZWG9/W}OoPTiB,X|[s}Lf]YFqSEQ]WEl3yV;?FcjH/9_P"
  WORDPRESS_NONCE_SALT: "m>eY]oq,F2/;lU@6*YO/@mVm%kx3:^81]k46d%J)cY!|t{E_#2FhQX]A}_5}1lM`"

## Dependencies
percona-xtradb-cluster:
  enabled: true
  image:
    tag: 5.7.19
  replicas: 2
  mysqlUser: wordpress
  mysqlDatabase: wordpress
  mysqlPassword: "4qIP58G7tcDUfHMgXTW20x0d"
  mysqlRootPassword: "3755GuzWP6dFubm3g3mY3Pwn"
  xtraBackupPassword: "8juqGFajT9aBmyOS3jQ3UXeO"
  persistence:
    enabled: false
    storageClass: nfs-04
    size: 64Gi
  metricsExporter: true

nfs-server-provisioner:
  enabled: true
  replicaCount: 1
  # imagePullSecrets:
  image:
    repository: quay.io/kubernetes_incubator/nfs-provisioner
    tag: v1.0.9
    pullPolicy: Always
  service:
    type: ClusterIP
    nfsPort: 2049
    mountdPort: 20048
    rpcbindPort: 51413
    externalIPs: []
  persistence:
    # this is persistence for the nfs server 'under the hood'
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 32Gi
  storageClass:
    create: true
    defaultClass: false
    name: nfs-wp
  rbac:
    create: true
    serviceAccountName: default
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
