dependencies:
- name: nfs-server-provisioner
  version: 0.1.5
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - storage
- name: mariadb
  version: 5.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - database
