replicaCount: 1

image:
  repository: wordpress
  tag: 4.9.8
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# used only if percona-xtradb-cluster is disabled
externalDB:
  host: ""
  name: ""
  user: ""
  password: ""

php:
  max-upload-size: 256M # should correspond to what you configure for your ingress
  additional-ini: "" # ability to add multi-line string with additional php.ini contents

ingress:
  enabled: true
  annotations: {}
    ## allow larger uploads/requests than default 2m
    # nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    # kubernetes.io/ingress.class: nginx
    ## cert-manager for ACME/LetsEncrypt - autogenerate cert
    # kubernetes.io/tls-acme: "true"
    ## Force SSL redirects for nginx-ingress
    # ingress.kubernetes.io/force-ssl-redirect: "true"
    ## sticky sessions with nginx-ingress
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "wplbsession"
    # nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
  path: /
  hosts:
    - domain.tld
  tls:
    - secretName: domain-tld-tls
      hosts:
        - domain.tld
persistence:
  enabled: true
  storageClass: "-" # specified value only works if nfs-server-provisioner is disabled or does not create a storageClass
  accessMode: ReadWriteMany
  size: 32Gi


resources:
  requests:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

env:
  WORDPRESS_TABLE_PREFIX: wp_
  WORDPRESS_DEBUG: "0"

# you can get 'fresh salt' from here: https://api.wordpress.org/secret-key/1.1/salt/
secrets:
  WORDPRESS_AUTH_KEY: ""
  WORDPRESS_SECURE_AUTH_KEY: ""
  WORDPRESS_LOGGED_IN_KEY: ""
  WORDPRESS_NONCE_KEY: ""
  WORDPRESS_AUTH_SALT: ""
  WORDPRESS_SECURE_AUTH_SALT: ""
  WORDPRESS_LOGGED_IN_SALT: ""
  WORDPRESS_NONCE_SALT: ""

## Dependencies
tags:
  database: true
  storage: true

percona-xtradb-cluster:
  image:
    tag: 5.7.19
  replicas: 2
  mysqlUser: wordpress
  mysqlDatabase: wordpress
  mysqlPassword: ""
  mysqlRootPassword: ""
  xtraBackupPassword: ""
  persistence:
    enabled: false
    storageClass: "-"
    size: 32Gi
  metricsExporter: false

nfs-server-provisioner:
  replicaCount: 1
  # imagePullSecrets:
  service:
    type: ClusterIP
    nfsPort: 2049
    mountdPort: 20048
    rpcbindPort: 51413
    externalIPs: []
  persistence:
    # this is persistence for the nfs server 'under the hood'
    enabled: true
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 32Gi
  storageClass:
    create: true
    defaultClass: false
    name: nfs-wp
  rbac:
    create: true
    serviceAccountName: default
