apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ansible-awx.fullname" . }}-awx-env
  labels:
    app: {{ template "ansible-awx.name" . }}
    chart: {{ template "ansible-awx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.default_admin_password }}
  AWX_ADMIN_PASSWORD: {{ .Values.default_admin_password | b64enc | quote }}
{{- else }}
  AWX_ADMIN_PASSWORD: {{ randAlphaNum 12 | b64enc | quote }}
{{- end}}
{{- if .Values.awx_secret_key }}
  AWX_SECRET_KEY: {{ .Values.awx_secret_key | b64enc | quote }}
{{- else }}
  AWX_SECRET_KEY: {{ randAlphaNum 12 | b64enc | quote }}
{{- end }}
