apiVersion: v1
kind: Service
metadata:
  name: {{ template "ansible-awx.fullname" . }}
  labels:
    app: {{ template "ansible-awx.name" . }}
    chart: {{ template "ansible-awx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.awx_web.service.type }}
  ports:
    - port: {{ default "80" .Values.awx_web.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "ansible-awx.name" . }}-awx-web
    release: {{ .Release.Name }}
